spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/libarydb
    username: postgres
    password: secret
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'


