spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/libarydb2
    username: postgres
    password: secret
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create


