@startuml
set separator none
title Rental

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ModulithLibraryApplication.ModulithLibraryApplication_boundary", "Application", $tags="") {
  Component(ModulithLibraryApplication.ModulithLibraryApplication.Events, "Events", $techn="Module", $descr="", $tags="", $link="")
  Component(ModulithLibraryApplication.ModulithLibraryApplication.Rental, "Rental", $techn="Module", $descr="", $tags="", $link="")
}

Rel(ModulithLibraryApplication.ModulithLibraryApplication.Rental, ModulithLibraryApplication.ModulithLibraryApplication.Events, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml